user-guide/introduction/quickstart.njk
Adjusted grammar on line #13 & fixed broken link on line #15
=> Fixed broken link & grammar

technical-guide/configuration.md
Added to the 63 row informations about the oauth callback URI configurations.
=> Add callback oauth URI instructions

technical-guide/configuration.md, technical-guide/developer/devenv.md
Signed-off-by: snack <rollingsnack831@gmail.com>
=> Fix missing highlight code blocks

_includes/layouts/base.njk
Developer guide -> Technical guide
=> Fix broken link in the footer (#26)

technical-guide/developer/devenv.md
- Rewording to improve readability.
- Add detail of how to access devenv penpot web interface
=> :books: Minor update adding some extra details to devenv

user-guide/introduction/shortcuts.njk
This PR solves a task in [Taiga #896](https://tree.taiga.io/project/penpot/us/896)
=> :sparkles: Add viewer zoom shortcuts

user-guide/introduction/shortcuts.njk
This is related to https://github.com/penpot/penpot/pull/1439
=> :sparkles: Add move shortcut

user-guide/libraries/index.njk
This issue closes (Taiga #2438)[https://tree.taiga.io/project/penpot/task/2438]
=> :recycle: Change shortcut for "add color from library to stroke"

user-guide/introduction/shortcuts.njk
This PR solves [this task](https://tree.taiga.io/project/penpot/task/3280)
=> :recycle: Shortcuts redo

user-guide/introduction/shortcuts.njk
This PR solves problems detected  [here](https://tree.taiga.io/project/penpot/task/3280)
=> :bug: Fix problems detected during QA

_includes/layouts/base.njk, faqs.njk, index.njk, user-guide/introduction/info.njk
Do not publish this changes before June 29
=> :lipstick: Community access

user-guide/grids-and-layouts/index.njk, user-guide/introduction/shortcuts.njk, user-guide/the-interface/index.njk
This PR solves https://tree.taiga.io/project/penpot/issue/4215
=> :bug: Fix typo

contributing-guide/reporting-bugs/index.njk
Changing the sentence regarding asking the user to send them an email if they want to discuss any issues privately.
=> Correcting language

technical-guide/developer/devenv.md
Fixed an error in devenv.md file.
=> Updated devenv.md

user-guide/objects/index.njk
Changed a few "an board" to "a board"
also one spelling correction for "typically"
=> Grammar corrections

css/index.css, js/search.js
Fixes https://tree.taiga.io/project/penpot/issue/4542
=> :bug: Fix search box misalingment when its active

technical-guide/configuration.md, technical-guide/developer/architecture/backend.md, technical-guide/developer/architecture/common.md, technical-guide/developer/architecture/exporter.md, technical-guide/developer/architecture/frontend.md, technical-guide/developer/architecture/index.md, technical-guide/developer/backend.md, technical-guide/developer/common.md, technical-guide/developer/data-guide.md, technical-guide/developer/data-model/index.md, technical-guide/developer/devenv.md, technical-guide/developer/frontend.md, technical-guide/developer/index.md, technical-guide/developer/subsystems/assets-storage.md, technical-guide/developer/subsystems/authentication.md, technical-guide/developer/subsystems/index.md, technical-guide/getting-started.md, technical-guide/index.md
*DO NOT MERGE* until new docker-compose organization is available in Penpot public images.
=> :books: Refactor self-hosting guide

css/index.css
We have defined few color variables so I replace them with HEX values.
There is one change in visual design:
- I changed background for code snippets to match new defined pallete
=> :sparkles: connect missing color variables to values

technical-guide/getting-started.md
Hi! Noticed this minor issue of incorrect hyperlinking, so thought to fix this. This is the only occurrence of this specific issue.
Thanks!
Signed-off by: Prince-Mendiratta
=> Update incorrect link for configuration on getting started page

user-guide/custom-fonts/index.njk, user-guide/import-export/index.njk, user-guide/teams/index.njk
Fix grammatical errors described in #152
=> :books: Fix grammatical errors

faqs.njk, user-guide/components/index.njk, user-guide/custom-fonts/index.njk, user-guide/exporting/index.njk, user-guide/flexible-layouts/index.njk, user-guide/import-export/index.njk, user-guide/inspect/index.njk, user-guide/introduction/quickstart.njk, user-guide/introduction/shortcuts.njk, user-guide/layer-basics/index.njk, user-guide/libraries/index.njk, user-guide/prototyping/index.njk, user-guide/styling/index.njk, user-guide/teams/index.njk, user-guide/the-interface/index.njk, user-guide/view-mode/index.njk, user-guide/workspace-basics/index.njk
This PR fixes some minor typos in the `user-guide`. It also updates some sentences to be more clear. It was useful and it was fun to go over the whole documentation.
=> Little improvements in user guide

user-guide/teams/index.njk
I was reading up and noticed some typos :)
=> Fix typos on Teams page in User guide

technical-guide/configuration.md
Trivial update fixing typos in the technical configuration guide.
=> Fix typos in technical configuration guide

technical-guide/plugins/create-a-plugin.md
=> :lipstick: Improve plugin creation steps docs

technical-guide/plugins/create-a-plugin.md
⚠️ Question: All image formats should be valid?
=> :sparkles: add icon docs and improve structure

technical-guide/developer/frontend.md, technical-guide/developer/ui.md
Closes https://tree.taiga.io/project/penpot/task/8596
=> :books: Add UI guide to the technical guide page

technical-guide/developer/ui.md
Closes https://tree.taiga.io/project/penpot/task/8597
=> :books: Add Storybook documentation

_includes/layouts/base.njk
This PR solves [this task](https://tree.taiga.io/project/penpot/task/8667)
=> 🐛 Fix footer links

user-guide/introduction/quickstart.njk
Removed an unnecessary comma at the introduction
=> :lipstick: Removed comma on quickstart.njk

user-guide/the-interface/index.njk
Changing the order to be more logical for the reader
=> :sparkles: updating the interface section to include "your account" and update the Light mode section to UI Theme

.eleventy.js
Fixes https://tree.taiga.io/project/penpot/issue/8751
=> :bug: Fix search tool to access the full contents of the pages
